FROM python:alpine3.20 AS base

ARG DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
ARG DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
ARG DISCORD_ROLE_DISCORD_BOOSTER_ID=${DISCORD_ROLE_DISCORD_BOOSTER_ID}
ARG DISCORD_ROLE_TWITCH_SUB_ID=${DISCORD_ROLE_TWITCH_SUB_ID}
ARG DISCORD_ROLE_SUPPORTERS_ID=${DISCORD_ROLE_SUPPORTERS_ID}

ENV DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
ENV DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
ENV DISCORD_ROLE_DISCORD_BOOSTER_ID=${DISCORD_ROLE_DISCORD_BOOSTER_ID}
ENV DISCORD_ROLE_TWITCH_SUB_ID=${DISCORD_ROLE_TWITCH_SUB_ID}
ENV DISCORD_ROLE_SUPPORTERS_ID=${DISCORD_ROLE_SUPPORTERS_ID}

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["main.lambda_handler"]

# --- Stage for Local Development ---

FROM base AS local
CMD ["python", "src/main.py"]