name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          # Add your test commands here
          echo "Running tests..."

      - name: Build Docker image
        run: docker build -t scriptkitty-lambda-function .

      - name: Authenticate to AWS ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 058264132929.dkr.ecr.ap-northeast-1.amazonaws.com
  
      - name: Tag Docker image
        run: docker tag my-lambda-function:latest 058264132929.dkr.ecr.ap-northeast-1.amazonaws.com/my-lambda-function:latest
  
      - name: Push Docker image to ECR
        run: docker push 058264132929.dkr.ecr.ap-northeast-1.amazonaws.com/my-lambda-function:latest
  
      - name: Deploy to AWS using Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          ROLE_TWITCHSUB_ID: ${{ secrets.DISCORD_ROLE_TWITCH_SUB_ID }}
          ROLE_BOOSTER_ID: ${{ secrets.DISCORD_ROLE_DISCORD_BOOSTER_ID }}
          ROLE_SUPPORTER_ID: ${{ secrets.DISCORD_ROLE_SUPPORTERS_ID }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve