name: Build and Deploy nyankoronikki

on:
  push:
    branches:
      - feature/nyankoronikki-fargate

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトリポジトリ / Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
        run: terraform plan -var "container_image=${CONTAINER_IMAGE}" \
                            -var "openai_api_key=${OPENAI_API_KEY}" \
                            -var "pinecone_api_key=${PINECONE_API_KEY}" \
                            -var "pinecone_environment=${PINECONE_ENVIRONMENT}" \
                            -lock=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/feature/nyankoronikki-fargate'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
        run: terraform apply -auto-approve \
                            -var "container_image=${CONTAINER_IMAGE}" \
                            -var "openai_api_key=${OPENAI_API_KEY}" \
                            -var "pinecone_api_key=${PINECONE_API_KEY}" \
                            -var "pinecone_environment=${PINECONE_ENVIRONMENT}" \
                            -lock=false
