name: nyankoronikki Fargate Deploy

on:
  push:
    branches:
      - main        # or your deployment branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: にゃんころ日記
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-1
      CONTAINER_IMAGE: ${{ secrets.CONTAINER_IMAGE }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="container_image=${CONTAINER_IMAGE}" \
            -var="openai_api_key=${OPENAI_API_KEY}" \
            -var="pinecone_api_key=${PINECONE_API_KEY}" \
            -var="pinecone_environment=${PINECONE_ENVIRONMENT}" \
            -lock=false

      - name: Terraform Apply
        run: |
          terraform apply \
            -var="container_image=${CONTAINER_IMAGE}" \
            -var="openai_api_key=${OPENAI_API_KEY}" \
            -var="pinecone_api_key=${PINECONE_API_KEY}" \
            -var="pinecone_environment=${PINECONE_ENVIRONMENT}" \
            -lock=false \
            -auto-approve
