name: nyankoronikki Fargate Deploy

on:
  push:
    branches:
      - main           # 自動で main ブランチにプッシュされたときに実行
  workflow_dispatch:   # 手動で「Run workflow」ボタンからも実行可能

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan \
              -var="container_image=${{ secrets.CONTAINER_IMAGE }}" \
              -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
              -var="pinecone_api_key=${{ secrets.PINECONE_API_KEY }}" \
              -var="pinecone_environment=${{ secrets.PINECONE_ENVIRONMENT }}"

      - name: Terraform Apply
        run: terraform apply -var="container_image=${{ secrets.CONTAINER_IMAGE }}" \
                             -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}" \
                             -var="pinecone_api_key=${{ secrets.PINECONE_API_KEY }}" \
                             -var="pinecone_environment=${{ secrets.PINECONE_ENVIRONMENT }}" \
                             -auto-approve
